### ISSUE TITLE
I'd like to ignore the auto-generated route of the page I am using the router extras in

### ISSUE THREAD

**Issue by CodyBontecou** [nuxt-community/router-extras-module#154]
Say I have a page `example.vue` with the following `<router>` property:

```yaml
<router>
  alias:
  - path: '/event/:id'
  - path: '/:username/:eventName/:eventCount'
</router>
```

My generated router.js looks like:

```js
{
    path: '/example',
    component: _4e18dbd1,
    name: 'example',
},
{
    path: '/event/:id',
    component: _4e18dbd1,
    name: 'example/event/:id',
},
{
    path: '/:username/:eventName/:eventCount',
    component: _4e18dbd1,
    name: 'example/:username/:eventName/:eventCount',
},
```

Is it possible to remove the `/example` route altogether? Or is the expected solution to this to create an `example/event/_id.vue` file with the router logic placed in there?
